connectApp/urls.py
from django.contrib import admin
from django.urls import path
from .views import LoginView, LogoutView, SignupAPIView,SidebarView, RedirectShopifyView, AuthorizeShopifyView, AuthorizeGoogleViewV2, CallBackGoogle,PullShopifydata,SyncShopifydata
app_name = 'connectApp'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('signup/', SignupAPIView.as_view(), name='sign_up'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('redirect/sidebar', SidebarView.as_view(), name='sidebar'),
    path('shopify/redirect', RedirectShopifyView.as_view(), name='redirect_shopify'),
    path('shopify/authorize', AuthorizeShopifyView.as_view(), name='authorize_shopify'),
    path('google/authorize', AuthorizeGoogleViewV2.as_view(), name='authorize_google'),
    path('callback_google', CallBackGoogle.as_view(), name='callbackGoogle'),
    path('sync_data', SyncShopifydata.as_view(), name='sync_data'),
    path('get_data', PullShopifydata.as_view(), name='get_data'),
]

connection_project/urls.py
from django.contrib import admin
from django.urls import path, include
from connectApp.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('connectApp.urls'))
]

connectApp/models.py
from django.db import models

class UserConnections(models.Model):
    class Platform(models.TextChoices):
        SHOPIFY = 'shopify'
        GOOGLE = 'google'
    user_id = models.CharField(max_length=100)
    access_token =  models.CharField(max_length=250, default='')
    platform = models.CharField(max_length=100, choices=Platform.choices)
    shop = models.CharField(max_length=100, default='')
    refresh_token = models.CharField(max_length=250, default='')
    spreadsheet_id = models.CharField(max_length=250, default='')
    
    
class ShopifyData(models.Model):
    user_id = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    product_id = models.CharField(max_length=100)
    product_type = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    vendor = models.CharField(max_length=100)
    created_at = models.DateTimeField()  
    updated_at = models.DateTimeField()
    is_deleted = models.BooleanField(default=False)
    row_range = models.CharField(max_length=100, default='')
    sync_flag = models.CharField(max_length=10, default='pending')

    def __str__(self):
        return f"{self.title} - {self.product_id}"

connectApp/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .seriallizers import UserSerializer
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
import requests, json
from .models import UserConnections, ShopifyData
from django.contrib import messages
from google_auth_oauthlib.flow import InstalledAppFlow
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime, timedelta, timezone

SCOPES_GOOGLE = ['https://www.googleapis.com/auth/spreadsheets']
REDIRECT_URL_GOOGLE = "http://localhost:9000/api/callback_google"

def create_spread_sheet(user_id, sheet_name):
    try:
        user = UserConnections.objects.get(user_id=user_id, platform='google')
        data = {}
        values =  [ {
                        "userEnteredValue": {
                            "stringValue": "title"
                        }
                        },
                        {
                        "userEnteredValue": {
                            "stringValue": "product_id"
                        }
                        },
                        {
                        "userEnteredValue": {
                            "stringValue": "product_type"
                        }
                        },
                        {
                        "userEnteredValue": {
                            "stringValue": "price"
                        }
                        },
                        {
                        "userEnteredValue": {
                            "stringValue": "vendor"
                        }
                        },
                        {
                        "userEnteredValue": {
                            "stringValue": "created_at"
                        }
                        },
                        {
                        "userEnteredValue": {
                            "stringValue": "updated_at"
                        }
                        }]

        url = "https://sheets.googleapis.com/v4/spreadsheets"

        payload = json.dumps({
        "properties": {
            "title": sheet_name
        },
        "sheets": [
            {
            "data": [
                {
                "rowData": [
                    {
                    "values": values
                    }
                ]
                }
            ],
            "properties": {
                "title": "Sheet1"
            }
            }
        ]
        })
        headers = {
        'Authorization': f'Bearer {user.access_token}',
        'Content-Type': 'application/json'
        }
        response = requests.request("POST", url, headers=headers, data=payload)
        if response.status_code==200:
            response=response.json()
            google_user, created = UserConnections.objects.update_or_create(
            user_id=user_id,
            platform='google',
            defaults={'spreadsheet_id': response['spreadsheetId']}
        )
            return True
        return False
    except Exception as e:
        return False

def get_flow(client_id, client_secret, project_id):
    flow = InstalledAppFlow.from_client_config(
    {
        "installed": {
            "client_id": client_id,
            "client_secret": client_secret,
            "project_id": project_id,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://accounts.google.com/o/oauth2/token",
        }
    },
    scopes=SCOPES_GOOGLE,
    redirect_uri=REDIRECT_URL_GOOGLE,
    )
    return flow

def sync_check(user_id):
    try:
        user_data = UserConnections.objects.filter(user_id=user_id).all()
        sync_response={'google_synced': False, 'is_spreadsheet': False, 'shopify_synced': False}

        data_dict = {
            'google_access_token': None,
            'shopify_access_token': None,
            'shop': None,
            'spreadsheet_id': None
        }

        for connection in user_data:
            platform = connection.platform
            data_dict[f'{platform}_access_token'] = connection.access_token
            if platform == 'shopify':
                data_dict['shop'] = connection.shop
            else:
                data_dict['spreadsheet_id'] = connection.spreadsheet_id

        if data_dict['spreadsheet_id']:
            sync_response['is_spreadsheet']=True

        if any(value is None for value in data_dict.values()):
            return sync_response

        shopify_url = f"https://{data_dict['shop']}.myshopify.com/admin/api/2024-01/products.json"
        shopify_header = {
            'Content-Type': 'application/json',
            'X-Shopify-Access-Token': data_dict['shopify_access_token']
            }
        shopify_response = requests.get(shopify_url, headers=shopify_header)
        if shopify_response.status_code == 200:
            sync_response['shopify_synced']=True
        google_url = f"https://sheets.googleapis.com/v4/spreadsheets/{data_dict['spreadsheet_id']}/values/Sheet1!A1:Z1"
        google_response = requests.get(google_url, headers={'Authorization': f'Bearer {data_dict["google_access_token"]}'})
        if google_response.status_code == 200:
            sync_response['google_synced']=True
        return sync_response
    except Exception:
        return {'google_synced': False, 'is_spreadsheet': False, 'shopify_synced': False}

class SignupAPIView(View):
    def post(self, request): 
        serializer = UserSerializer(data=request.POST)
        if serializer.is_valid():
            serializer.save()
            return redirect('connectApp:login')
        return HttpResponse(serializer.errors, status=400)

    def get(self, request):
        return render(request, 'signup.html')


@method_decorator(login_required, name='dispatch')
class SidebarView(View):
    def get(self, request):
        user_id = request.session['user_id']
        is_synced = sync_check(user_id)
        return render(request, 'sidebar.html', is_synced)


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            request.session['user_id'] = user.id
            is_synced = sync_check(user.id)
            print('synceddddddddddddddddddddd', is_synced)
            return render(request, 'sidebar.html', is_synced)
        else:
            return render(request, 'login.html', {'error': 'Invalid login credentials'})


@method_decorator(login_required, name='dispatch')
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('connectApp:login')


class RedirectShopifyView(View):
    def get(self, request):
        return render(request, 'success_shopify.html')


@method_decorator(login_required, name='dispatch')
class AuthorizeShopifyView(View):
    def get(self, request):
        shop = request.GET.get('shop')
        access_token = request.GET.get('access_token')
        user_id = request.session.get('user_id', '')
        url = f"https://{shop}.myshopify.com/admin/api/2024-01/products.json"
        payload = {}
        headers = {
            'Content-Type': 'application/json',
            'X-Shopify-Access-Token': access_token
        }
        response = requests.get(url, headers=headers, data=payload)

        if response.status_code == 200:
            google_user, created = UserConnections.objects.update_or_create(
                user_id=user_id,
                platform='shopify',
                defaults={
                    'access_token': access_token,
                    'shop': shop
                }
            )
            return render(request, 'success_shopify.html')
        else:
            messages.error(request, 'Failed to fetch data from Shopify API. Invalid credentials.')
            return render(request, 'error_shopify.html')


@method_decorator(login_required, name='dispatch')
class AuthorizeGoogleViewV2(View):
    def get(self, request):
        client_id = request.GET.get('client_id')
        client_secret = request.GET.get('client_secret')
        project_id = request.GET.get('project_id')
        spread_sheet_name = request.GET.get('spreadsheet_name')
        request.session['client_id'] = client_id
        request.session['client_secret'] = client_secret
        request.session['project_id'] = project_id
        request.session['spreadsheet_name'] = spread_sheet_name
        flow = get_flow(client_id, client_secret, project_id)
        authorization_url, _ = flow.authorization_url(prompt='consent')
        return redirect(authorization_url)


@method_decorator(login_required, name='dispatch')
class CallBackGoogle(View):
    def get(self, request):
        authorization_code = request.GET.get("code")
        client_id=request.session['client_id']
        client_secret=request.session['client_secret']
        project_id=request.session['project_id']
        user_id=request.session['user_id']
        flow = get_flow(client_id, client_secret, project_id)
        credentials = flow.fetch_token(
            authorization_response=f"{REDIRECT_URL_GOOGLE}?code={authorization_code}",
            **{"insecure_transport": True}
        )

        google_user, created = UserConnections.objects.update_or_create(
            user_id=user_id,
            platform='google',
            defaults={
                'access_token': credentials["access_token"],
                'refresh_token': credentials["refresh_token"]
            }
        )
        if not google_user.spreadsheet_id:

connectApp/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <style>
      body {
        font-family: "Arial", sans-serif;
        background: #f2f2f2;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
      }

      .login-container {
        background: #fff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        width: 400px;
        max-width: 100%;
      }

      .login-header {
        background: green;
        color: #fff;
        text-align: center;
        padding: 20px;
      }

      .login-form {
        padding: 20px;
      }

      .form-group {
        margin-bottom: 20px;
      }

      label {
        display: block;
        margin-bottom: 8px;
        color: #333;
      }

      input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
      }

      button {
        background: green;
        color: #fff;
        padding: 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
      }

      button:hover {
        background: #25c325;
      }

      .signup-link {
        text-align: center;
        margin-top: 10px;
      }

      .signup-link a {
        color: green;
        text-decoration: none;
        font-weight: bold;
      }

      .signup-link a:hover {
        text-decoration: underline;
      }

      .error {
        color: #ff0000;
        margin-bottom: 10px;
      }
    </style>
  </head>
  <body>
    <div class="login-container">
      <div class="login-header">
        <h2>Login</h2>
      </div>
      <div class="login-form">
        <form method="post" action="{% url 'connectApp:login' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" name="username" required />
          </div>
          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" required />
          </div>
          <button type="submit">Login</button>
          <p class="error">{{ error }}</p>
        </form>
      </div>
      <div class="signup-link">
        <p>
          If you don't have an account,
          <a href="{% url 'connectApp:sign_up' %}">signup here</a>.
        </p>
      </div>
    </div>
  </body>
</html>

connectApp/templates/shopify_data.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Pulled Data</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            padding: 20px;
            background-color: #f8f9fa; /* Set a light background color */
        }

        h1 {
            color: #11de0a; /* Set the color for the h1 header */
        }

        .table-container {
            margin-top: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            overflow: hidden;
        }

        .table-header {
            background-color: #11de0a; /* Set the background color for the table header */
            color: rgb(10, 9, 9);
        }

        .table-header th {
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
        }

        .table tbody tr:hover {
            background-color: rgba(0, 123, 255, 0.1);
        }

        .table tbody td {
            text-align: center;
            vertical-align: middle;
        }
        .pagination {
        display: flex;
        justify-content: center;
        margin-top: 20px;
        }

        .pagination a {
            color: #007bff;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color 0.3s;
            border: 1px solid #007bff;
            margin: 0 4px;
            border-radius: 5px;
        }

        .pagination a:hover {
            background-color: #007bff;
            color: #fff;
        }

        .pagination .current {
            background-color: #007bff;
            color: #fff;
            padding: 8px 16px;
            border: 1px solid #007bff;
            margin: 0 4px;
            border-radius: 5px;
        }
        .go-back-btn {
            background-color: #007bff;
            color: #ffffff;
            padding: 8px 23px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        .go-back-btn:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <h1>Shopify Data</h1>

    {% if data %}
    <div class="table-container">
        <table class="table table-bordered">
            <thead class="table-header">
                <tr>
                    <th>Title</th>
                    <th>Product ID</th>
                    <th>Product Type</th>
                    <th>Vendor</th>
                    <th>Sync Flag</th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.product_id }}</td>
                    <td>{{ item.product_type }}</td>
                    <td>{{ item.vendor }}</td>
                    <td>{{ item.sync_flag }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>No data available.</p>
    {% endif %}
<!-- Pagination controls -->
    <div class="pagination">
        <span class="step-links">
            {% if data.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ data.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ data.number }} of {{ data.paginator.num_pages }}.
            </span>

            {% if data.has_next %}
            <a href="?page={{ data.next_page_number }}">next</a>
            <a href="?page={{ data.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
            <button class="go-back-btn" onclick="goBack()">Go Back</button>

        </span>
    </div>
    <script>
        function goBack() {
            window.location.href = '{% url "connectApp:sidebar" %}';
        }
    </script>

    <!-- Bootstrap JavaScript (optional, but may be needed for certain Bootstrap features) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

connectApp/templates/sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Connections</title>
    <style>
      body {
        margin: 0;
        font-family: "Arial", sans-serif;
      }

      .sidebar {
        height: 100%;
        width: 250px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        padding-top: 20px;
      }

      .sidebar .header {
        text-align: center;
        padding-bottom: 20px;
      }

      .sidebar .header h2 {
        color: white;
      }

      .buttons {
        display: flex;
        flex-direction: column;
      }

      .sidebar a {
        padding: 10px 16px;
        text-decoration: none;
        font-size: 18px;
        color: white;
        display: flex;
        align-items: center;
        transition: background-color 0.3s;
      }

      .sidebar a img {
        width: 24px;
        height: 24px;
        margin-right: 10px;
      }

      .sidebar a:hover {
        background-color: #ddd;
        color: black;
      }

      .content {
        margin-left: 250px;
        padding: 16px;
      }

      /* Popup styling */
      .popup {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: white;
        padding: 40px; /* Increased padding for a larger appearance */
        z-index: 2;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
        max-width: 500px; /* Adjust width as needed */
        width: 100%;
        box-sizing: border-box;
      }

      .popup input {
        margin-bottom: 20px;
        width: 100%;
        box-sizing: border-box;
        padding: 10px; /* Increased padding for input fields */
      }

      .popup button {
        padding: 15px; /* Increased padding for the button */
        cursor: pointer;
        width: 100%;
        box-sizing: border-box;
      }
      /* Sync Button */
      .btn-oval {
        display: inline-block;
        width: 200px;
        top: 260px;
        height: 50px;
        box-sizing: border-box;
        text-align: center; 
        line-height: 70px;
        color: #fff;
        text-decoration: none;
        background: linear-gradient(#89c13e, #599c02);
        background-color: #6fad1d;
        border-radius: 32px;
        border: 1px solid #579a00;
        font: bold 30px/70px Arial;
        box-shadow: inset 0 2px 2px #cce464, inset 1px 0 3px #b2dc2d,
          inset -1px 0 3px #b2dc2d, inset 0 -2px 2px #89d301,
          0 0 3px rgba(0, 0, 0, 0.24);
        position: relative;
        text-shadow: 0 1px #45880d;
        outline: none;
      }
      .btn-oval:before {
        content: "";
        position: absolute;
        top: -8px;
        left: -10px;
        width: 99%;
        height: 87%;
        padding: 10px;
        background: #d7d7d7;
        z-index: -1;
        border-radius: 50px;
        box-shadow: inset 0 1px 2px #bbb;
      }
      .btn-oval:hover {
        background: linear-gradient(#97d444, #65ad07);
        box-shadow: inset 0 1px 0 #e2f498, inset 0 2px 0 #ceec87,
          inset 0 3px 0 #c3e67c, inset 0 5px 0 #bae475, inset 1px 0 3px #b2dc2d,
          inset -1px 0 3px #b2dc2d, inset 0 -2px 2px #89d301,
          0 0 3px rgba(0, 0, 0, 0.24);
      }
      .btn-oval:active {
        background: linear-gradient(#83bb37, #599c02);
        box-shadow: inset 0 3px 7px #3c7b00;
        padding: 1px 0 0 1px;
      }

      /* Center Button */
      body {
        display: flex;
        min-height: 100vh;
      }
      .btn-oval {
        margin: auto;
      }

      btn-oval + .btn-oval {
          margin-left: 30px; 
        }

      

      /* Responsive styling */
      @media (max-width: 768px) {
        .sidebar {
          width: 100%;
        }
        .content {
          margin-left: 0;
        }
      }
    </style>
  </head>
  <body>
    <div class="sidebar">
      <div class="header">
        <h2>Connections</h2>
      </div>
      <div class="buttons">
        <a href="#" onclick="showPopup('shopifyPopup')">
          <img src="{% static 'images/shopify_logo.png' %}" alt="Shopify" />
          Shopify
        </a>
        <a href="#" onclick="showPopup('googlePopup')">
          <img src="{% static 'images/google_logo.png' %}" alt="Google" />
          Google
        </a>
        {% if google_synced %}
        <a href="#" onclick="redirectToSync()" class="btn btn-oval">
          <img src="{% static 'images/new.jpg' %}" alt="sync_button" />
          SyncData
        </a>
      {% endif %}
      &nbsp;
      {% if shopify_synced %}
      <a href="#" onclick="redirectToPull()" class="btn btn-oval">
        <img src="{% static 'images/new.jpg' %}" alt="get_button" />
        getData
      </a>
      {% endif %}
      &nbsp;

      <div class="logout-container" style="position: fixed; top: 10px; right: 10px; z-index: 3;">
        <a href="#" onclick="logout()" style="color: rgb(0, 0, 0); cursor: pointer; text-decoration: none;">
          <img src="{% static 'images/logout-icon.png' %}" alt="Logout" style="width: 20px; height: 20px; margin-right: 5px;" />
          Logout
        </a>
      </div>
  
      </div>
    </div>

    <!-- Popup HTML -->
    <div class="popup" id="shopifyPopup">
      <label for="shopName">Enter Shop Name:</label>
      <input type="text" id="shopName" placeholder="Shop Name" />
      <label for="accessToken">Enter Access Token:</label>
      <input type="text" id="accessToken" placeholder="Access Token" />
      <button onclick="redirectToShopify()">Go</button>
    </div>

    <!-- Google Popup HTML -->
    <div class="popup" id="googlePopup">
      <label for="clientId">Enter Client ID:</label>
      <input type="text" id="clientId" placeholder="Client ID" />
      <label for="clientSecret">Enter Client Secret:</label>
      <input type="text" id="clientSecret" placeholder="Client Secret" />
      <label for="projectId">Enter Project ID:</label>
      <input type="text" id="projectId" placeholder="Project ID" />
      {% if not is_spreadsheet %}
      <label for="spreadsheetName">Enter spreadsheet name:</label>
      <input type="text" id="spreadsheetName" placeholder="Spreadsheet Name" />
      {% endif %}
      <button onclick="redirectToGoogle()">Go</button>
    </div>

    <script>
      function showPopup(popupId) {
        var popups = document.querySelectorAll('.popup');
        popups.forEach(function (popup) {
          popup.style.display = 'none';
        });

        document.getElementById(popupId).style.display = 'block';
      }

      function redirectToShopify() {
        var shopName = document.getElementById('shopName').value;
        var accessToken = document.getElementById('accessToken').value;

        if (shopName && accessToken) {
          window.location.href = '{% url "connectApp:authorize_shopify" %}?shop=' + shopName + '&access_token=' + accessToken;
        }
      }

      function redirectToSync() {
          window.location.href = '{% url "connectApp:sync_data" %}';
        
      }
      function redirectToPull() {
          window.location.href = '{% url "connectApp:get_data" %}';
        
      }
      function logout() {
        window.location.href = '{% url "connectApp:logout" %}';
        alert("Logout clicked!"); // Replace this with actual logout code
      }


      function redirectToGoogle() {
        var clientId = document.getElementById('clientId').value;
        var clientSecret = document.getElementById('clientSecret').value;
        var projectId = document.getElementById('projectId').value;
        var spreadsheetName = document.getElementById('spreadsheetName');
        var url = '{% url "connectApp:authorize_google" %}?client_id=' + clientId + '&client_secret=' + clientSecret + '&project_id=' + projectId
        if (spreadsheetName){
          url += '&spreadsheet_name=' + spreadsheetName.value
        }
        if (clientId && clientSecret && projectId) {
          window.location.href = url;
        }
      }
    </script>
  </body>
</html>

connectApp/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Signup</title>
    <style>
      body {
        font-family: "Arial", sans-serif;
        background: #f2f2f2;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
      }

      .signup-container {
        background: #fff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        width: 400px;
        max-width: 100%;
      }

      .signup-header {
        background: green;
        color: #fff;
        text-align: center;
        padding: 20px;
      }

      .signup-form {
        padding: 20px;
      }

      .form-group {
        margin-bottom: 20px;
      }

      label {
        display: block;
        margin-bottom: 8px;
        color: #333;
      }

      input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
      }

      button {
        background: green;
        color: #fff;
        padding: 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
      }

      button:hover {
        background: black;
      }

      .error {
        color: #ff0000;
        margin-bottom: 10px;
      }
    </style>
  </head>
  <body>
    <div class="signup-container">
      <div class="signup-header">
        <h2>Signup</h2>
      </div>
      <div class="signup-form">
        <form method="post" action="{% url 'connectApp:sign_up' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" name="username" required />
          </div>
          <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" required />
          </div>
          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" required />
          </div>
          <button type="submit">Signup</button>
          <p class="error">{{ error }}</p>
        </form>
      </div>
    </div>
  </body>
</html>

connectApp/templates/syncdata.html
<!-- templates/your_app/sync_response.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Sync Response</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            text-align: center;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
        }

        h1 {
            color: #333;
        }

        p {
            margin: 20px 0;
            font-size: 18px;
            color: #555;
        }

        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            font-size: 16px;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <header>
        <h1>Data Sync Response</h1>
    </header>
    <main>
        <p>{{ message }}</p>
        <button onclick="goBack()">Go Back</button>
    </main>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
</body>
</html>